title: Поездка в Таллинн
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4801779373083264
  brandStrength: 0.5124205220490694
  rhythmicContrast: 0.5506737474352121
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.7321334667503834
typography_spectrum: 0.2284836147446185
description: '2016'
layout_spectrum: 1
name: Tallinn
